import type { Theme } from '../theme'
import { THEME_SCHEMA_VERSION } from '../theme'

export const materialDark: Theme = {
  version: THEME_SCHEMA_VERSION,
  id: 'material-dark',
  name: 'Material Dark',
  type: 'dark',
  builtIn: true,
  author: 'Cate theme pack',
  bootBackground: '#212121',
  app: {
    'surface-0': '#212121',
    'surface-1': '#1a1a1a',
    'surface-2': '#252525',
    'surface-3': '#2c2c2c',
    'surface-4': '#333333',
    'surface-5': '#3a3a3a',
    'surface-6': '#424242',
    'titlebar-bg': '#1a1a1a',
    'canvas-bg': '#191919',
    'canvas-bg-alt': '#1e1e1e',
    'grid-dot': '#2a2a2a',
    'grid-line': '#252525',
    'border-subtle': '#141414',
    'border-strong': 'rgba(255, 255, 255, 0.12)',
    'border-focus': '#82aaff',
    'text-primary': '#eeffff',
    'text-secondary': '#b0bec5',
    'text-muted': '#607d8b',
    'text-inverse': '#212121',
    'focus-blue': '#82aaff',
    'activity-green': '#c3e88d',
    'activity-orange': '#ffcb6b',
    'shadow-node': 'rgba(0,0,0,0.55)',
    'shadow-node-focused': 'rgba(130,170,255,0.35)',
    'node-bg-active': '#252525',
    'node-dim-overlay': 'rgba(26,26,26,0.45)',
    'scrollbar-thumb': '#42424299',
    'scrollbar-thumb-hover': '#546e7acc',
    'surface-hover': '#2c2c2c',
    'surface-hover-strong': '#333333',
    'git-added': '#c3e88d',
    'git-modified': '#ffcb6b',
    'git-deleted': '#ff5370',
    'git-untracked': '#c3e88d',
    'git-renamed': '#82aaff',
    'agent-rgb': '130 170 255',
    'agent-light-rgb': '160 195 255',
  },
  terminal: {
    background: '#212121',
    foreground: '#eeffff',
    cursor: '#82aaff',
    selectionBackground: '#3c435a',
    black: '#546e7a', red: '#ff5370', green: '#c3e88d', yellow: '#ffcb6b',
    blue: '#82aaff', magenta: '#c792ea', cyan: '#89ddff', white: '#eeffff',
    brightBlack: '#607d8b', brightRed: '#ff5370', brightGreen: '#c3e88d', brightYellow: '#ffcb6b',
    brightBlue: '#82aaff', brightMagenta: '#c792ea', brightCyan: '#89ddff', brightWhite: '#ffffff',
  },
  editor: {
    base: 'vs-dark',
    colors: {
      'editor.background': '#212121',
      'editor.foreground': '#eeffff',
      'editor.selectionBackground': '#3c435a',
      'editor.lineHighlightBackground': '#2c2c2c',
      'editorCursor.foreground': '#82aaff',
      'editorLineNumber.foreground': '#37474f',
      'editorLineNumber.activeForeground': '#546e7a',
    },
    tokens: [
      { token: 'comment', foreground: '546e7a', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'c792ea' },
      { token: 'keyword.control', foreground: 'c792ea' },
      { token: 'storage', foreground: 'c792ea' },
      { token: 'storage.type', foreground: 'c792ea' },
      { token: 'string', foreground: 'c3e88d' },
      { token: 'constant.numeric', foreground: 'f78c6c' },
      { token: 'constant.language', foreground: 'f78c6c' },
      { token: 'constant', foreground: '89ddff' },
      { token: 'variable', foreground: 'eeffff' },
      { token: 'variable.parameter', foreground: 'f07178' },
      { token: 'type', foreground: 'ffcb6b' },
      { token: 'entity.name.type', foreground: 'ffcb6b' },
      { token: 'entity.name.class', foreground: 'ffcb6b' },
      { token: 'entity.name.function', foreground: '82aaff' },
      { token: 'support.function', foreground: '82aaff' },
      { token: 'entity.name.tag', foreground: 'f07178' },
      { token: 'entity.other.attribute-name', foreground: 'ffcb6b' },
      { token: 'operator', foreground: '89ddff' },
    ],
  },
}
